name: Publish tags to CMP deployment versions

on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Install JQ
      run: sudo apt install jq -y
    - name: Deploy version in all instances
      run: |
        curl -k -H "Content-Type: application/json" -H "Authorization: Bearer ${{secrets.CMP_TOKEN}}" -X POST "${{secrets.CMP_URL}}/api/instances/${{env.DEPLOYMENT_TEST.INSTANCE_ID}}/deploy" -d '{"appDeploy": {"instance": "${{env.DEPLOYMENT_TEST.INSTANCE_ID}}","deployment": "${{env.DEPLOYMENT_TEST.DEPLOYMENT_VERSION}}","version": "34"}}'
        
